[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38', 'py39', 'py310', 'py310']

[tool.pytest.ini_options]
filterwarnings = [
    "error:::marshmallow_dataclass|test",
]
